### ISSUE TITLE
Support ES6 style exports

### ISSUE THREAD

**Issue by ivan-kleshnin** [alexmingoia/jsx-transform#13]
**jsx-transform** throws on this line:
```javascript
export default View;
```

This works ok:
```javascript
module.exports = View;
```

```
Error: Parse Error: Line 24: Illegal export declaration
    at throwError (/Users/ivankleshnin/Projects/cycle-one/node_modules/gulp-jsx/node_modules/jsx-transform/node_modules/jstransform/node_modules/esprima-fb/esprima.js:2724:21)
    at throwErrorTolerant (/Users/ivankleshnin/Projects/cycle-one/node_modules/gulp-jsx/node_modules/jsx-transform/node_modules/jstransform/node_modules/esprima-fb/esprima.js:2736:24)
    at parseSourceElement (/Users/ivankleshnin/Projects/cycle-one/node_modules/gulp-jsx/node_modules/jsx-transform/node_modules/jstransform/node_modules/esprima-fb/esprima.js:6332:17)
    at parseProgramElement (/Users/ivankleshnin/Projects/cycle-one/node_modules/gulp-jsx/node_modules/jsx-transform/node_modules/jstransform/node_modules/esprima-fb/esprima.js:6391:16)
    at parseProgramElements (/Users/ivankleshnin/Projects/cycle-one/node_modules/gulp-jsx/node_modules/jsx-transform/node_modules/jstransform/node_modules/esprima-fb/esprima.js:6423:29)
    at parseProgram (/Users/ivankleshnin/Projects/cycle-one/node_modules/gulp-jsx/node_modules/jsx-transform/node_modules/jstransform/node_modules/esprima-fb/esprima.js:6436:16)
    at Object.parse (/Users/ivankleshnin/Projects/cycle-one/node_modules/gulp-jsx/node_modules/jsx-transform/node_modules/jstransform/node_modules/esprima-fb/esprima.js:7766:23)
    at getAstForSource (/Users/ivankleshnin/Projects/cycle-one/node_modules/gulp-jsx/node_modules/jsx-transform/node_modules/jstransform/src/jstransform.js:251:21)
    at transform (/Users/ivankleshnin/Projects/cycle-one/node_modules/gulp-jsx/node_modules/jsx-transform/node_modules/jstransform/src/jstransform.js:274:11)
    at Object.transform (/Users/ivankleshnin/Projects/cycle-one/node_modules/gulp-jsx/node_modules/jsx-transform/lib/jsx.js:53:21)
```

**Comment by alexmingoia** [comment]
jsx-transform uses jstransform (esprima) and implements a node visitor. To deal with ES6 would require rewriting with newer version of jsx-transform node visitor or using recast. I should have some time this week to do it.

**Comment by ivan-kleshnin** [comment]
That would be insanely helpful. You've already done a great work with all this.

**Comment by alexmingoia** [comment]
ES6 module exports should be working now... though I don't have any tests around other ES6 syntax. Let me know if you run into other issues.

**Comment by ivan-kleshnin** [comment]
I updated to `0.12` and observe bugs:

For example this code
```javascript
return <p>Started {delta} seconds ago</p>;
```

Is transormed to syntax error:
```javascript
return h('p', null, ["Started ", {delta,}" seconds ago"]);
```

**Comment by alexmingoia** [comment]
Crap... my tests weren't very comprehensive. This is fixed in 0.12.1

**Comment by alexmingoia** [comment]
I've also updated gulp-jsx with the latest version of jsx-transform.

**Comment by ivan-kleshnin** [comment]
Now works perfectly :thumbsup:
